from django.urls import path
from . import views

urlpatterns = [
    path("", views.landing, name="landing"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("register/", views.register, name="register"),
    path("trips/", views.trip_list, name="trip_list"),
    path("trips/new/", views.trip_create, name="trip_create"),
    path("trips/<int:pk>/", views.trip_detail, name="trip_detail"),
    path("trips/<int:pk>/edit/", views.trip_edit, name="trip_edit"),
    path("trips/<int:pk>/delete/", views.trip_delete, name="trip_delete"),
    path("trips/<int:pk>/duplicate/", views.trip_duplicate, name="trip_duplicate"),
    path("trips/<int:pk>/stop/add/", views.stop_add, name="stop_add"),
    path("trip-stops/<int:pk>/move/<str:direction>/", views.stop_move, name="stop_move"),
    path("trip-stops/<int:pk>/delete/", views.stop_delete, name="stop_delete"),
    path("trips/<int:pk>/expense/add/", views.expense_add, name="expense_add"),
    path("trips/<int:trip_pk>/days/<int:day_pk>/activity/add/", views.activity_add, name="activity_add"),
    path("itinerary-activities/<int:pk>/move/<str:direction>/", views.activity_move, name="activity_move"),
    path("itinerary-activities/<int:pk>/remove/", views.activity_remove, name="activity_remove"),
    path("trips/<int:pk>/share/", views.trip_share, name="trip_share"),
    path("shared/<uuid:token>/", views.shared_trip, name="shared_trip"),
    path("trips/<int:pk>/toggle-public/", views.toggle_public, name="toggle_public"),
    path("trips/<int:pk>/like/", views.like_trip, name="like_trip"),
    path("trips/<int:pk>/copy-public/", views.copy_public_trip, name="copy_public_trip"),
    path("explore/", views.explore, name="explore"),
    path("destinations/<int:pk>/save/", views.save_destination, name="save_destination"),
    path("destinations/<int:destination_pk>/add-to-trip/", views.add_destination_to_trip, name="add_destination_to_trip"),
    path("calendar/", views.calendar_view, name="calendar"),
    path("community/", views.community, name="community"),
    path("profile/", views.profile, name="profile"),
    path("profile/quick-update/", views.quick_profile_update, name="quick_profile_update"),
    path("profile/delete/", views.delete_account, name="delete_account"),
    path("admin-dashboard/", views.admin_dashboard, name="admin_dashboard"),
]
